name: todo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  path_provider: ^2.1.5
  path: ^1.9.0
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.3+1
  sqflite_common_ffi_web: ^0.4.3+3
  flutter_linkify: ^6.0.0
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # App icon
  flutter_launcher_icons: ^0.13.1

  # Native splash screen
  flutter_native_splash: ^2.4.3

# ------------------ APP ICON ------------------
flutter_icons:
  android: true
  ios: true
  image_path: assets/notee.png

# ------------------ NATIVE SPLASH ------------------
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/notee.png

  android: true
  ios: true
  web: false

  android_12:
    color: "#FFFFFF"
    image: assets/notee.png

# ------------------ FLUTTER ------------------
flutter:
  uses-material-design: true

  assets:
    - assets/notee.png
